[package]
name = "async_hw"
version = "0.1.0"
authors = ["Cl√©ment Nerma <clement.nerma@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.9.0"
lrvm = { path = "../../lrvm" }
lrvm_aux = { path = "../../lrvm_aux" }
lrvm_tools = { path = "../../lrvm_tools" }
